</div>
	</div>
	<script src="https://unpkg.com/@popperjs/core@2"></script>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/12065bbb1f.js" crossorigin="anonymous"></script>
        <script src="templates/scrollbot-master/scrollbot.js"></script>
        <script src="js/jquery_number.js"></script>
        <script>
            $(document).ready(function(){function t(){var t=[];$(".weapon-filter .item .weapon-item.active a.weapon-type").each(function(){t.push($(this).attr("data-target"))}),console.log($("#find-character").val().toLowerCase().trim()),$(".character-list .item a.char-direction").filter(function(){$(this).parent().toggle(t.includes($(this).attr("data-wp"))&&$(this).attr("title").toLowerCase().indexOf($("#find-character").val().toLowerCase().trim())>-1||t.includes($(this).attr("data-wp"))&&$(this).attr("data-original-title").toLowerCase().indexOf($("#find-character").val().toLowerCase().trim())>-1)})}$('[data-toggle="popover"]').popover(),$(".weapon-filter .item").on("click",function(){$(this).find(".weapon-item").toggleClass("active"),t()}),$("#find-character").on("keyup",function(){t()}),$(".image-collection .image-type .item").on("click",function(){var t;$(".image-collection .image-type .item").removeClass("current"),$(this).addClass("current"),t=$(this).attr("data-target"),$(".inner-content .quickview-info .image-collection .image-items .item").each(function(){$(this).attr("data-method").toLowerCase()==t.toLowerCase()?$(this).addClass("current"):$(this).removeClass("current")})}),$(".damage-calculator input").on("keyup change",function(){!function(){var t=$("#ATK_input").val()>=0?$("#ATK_input").val():0;if($("#crit-rate_input").val())if($("#crit-rate_input").val()>=0)if($("#crit-rate_input").val()<=100)var a=$("#crit-rate_input").val();else a=100;else a=0;else a=0;var e=$("#crit-DMG_input").val()>=0?$("#crit-DMG_input").val():0,i=$("#ele-sk-buff_input").val()>=0?$("#ele-sk-buff_input").val():0,n=$("#normal_atk_buff_input").val()>=0?$("#normal_atk_buff_input").val():0,r=$("#physic-buff_input").val()>=0?$("#physic-buff_input").val():0,l=($("#maxHP_input").val()>=0&&$("#maxHP_input").val(),$("#DEF_input_input").val()>=0&&$("#DEF_input_input").val(),parseInt(t*n/100*(1+r/100))),o=l*(1+parseInt(e)/100);$('p.DMG-output[data-target="physic"]').html($.number(l)+" / "+$.number(o));var u=parseInt(t*n/100*(1+i/100)),p=u*(1+parseInt(e)/100);$('p.DMG-output[data-target="element"]').html($.number(u)+" / "+$.number(p));var c=(parseInt(a)*o+parseInt(100-a)*l)/100;$('p.DMG-output[data-target="physic_overall"]').html($.number(parseInt(c)));var s=(parseInt(a)*p+parseInt(100-a)*u)/100;$('p.DMG-output[data-target="element_overall"]').html($.number(parseInt(s)))}()})});
        </script>
</body>
</html>